# Generated by Django 4.1.6 on 2023-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow')], default='disallow', max_length=10)),
                ('number_regex', models.CharField(max_length=255)),
            ],
        ),
    ]
