# Generated by Django 4.1.6 on 2023-02-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
