# Generated by Django 4.2.4 on 2023-08-24 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0007_user_invited_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="invited_by",
            new_name="created_by",
        ),
    ]
