# Generated by Django 4.2.4 on 2023-09-11 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0010_user_is_2fa_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="invited_by",
            new_name="created_by",
        ),
    ]
