# Generated by Django 4.2.4 on 2023-09-19 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0011_rename_invited_by_user_created_by"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_2fa_enabled",
        ),
    ]
