# Generated by Django 4.2.4 on 2023-10-04 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0012_alter_user_managers_remove_user_is_2fa_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
    ]
